date: now
date-modified: last-modified
date-format: "YYYY-MM-DDTHH:mm:ss zzz"
booklanguage: ja
monofont: "Ricty"
link-citations: true
fontsize: 12pt
project:
    type: website
    output-dir: docs
lang: ja
toc: true
format:
    html:
        css: 
            - css/gt.css
        html-math-method: katex
        include-in-header:
            - svgsnippet.html
metadata-files:
    - _website.yml
resources:
    - "img/*"
    - "img/*/*"
execute:
    message: false
    echo: false
    warning: false
    output: "asis"
params:
    gamever: 2024.07.09.0
license: "CC BY-SA"