project:
    type: website
    output-dir: docs
lang: ja
toc: true
format:
    html:
        css: syle.css
        html-math-method: katex
metadata-files:
    - _website.yml
resources:
    - "img/*"
    - "img/*/*"
execute:
    message: false
    echo: false
    warning: false
    output: "asis"
    keep-md: true
params:
    gamever: 2024.07.09.0