date: "2024-08-04T16:25:32"
date-modified: last-modified
date-format: "YYYY-MM-DDTHH:mm:ss JST"
author: "under-identified"
booklanguage: ja
license: "CC BY-SA"
monofont: "Ricty"
link-citations: true
fontsize: 14pt
project:
    type: website
    output-dir: public
lang: ja
language: custom-language.yml
toc: true
format:
    html:
        css:
            - css/gt.css
        html-math-method: katex
        include-in-header:
            - svgsnippet.html
        mainfont: '"Hiragino Sans","ヒラギノ角ゴ ProN W3","Yu Gothic",游ゴシック,"Noto Sans CJK JP",Arial,sans-serif'
        fontsize: 14pt
metadata-files:
    - _website.yml
resources:
    - "*.html"
    - "img/*"
    - "img/*/*"
execute:
    message: false
    echo: false
    warning: false
    output: "asis"
bibliography:
    - bibliography/HEMA.bib
    - bibliography/History.bib
bibliographystyle: chicago-author-date