---
title: "``Hellish Quart” のコマンド表"
author: "under-identified"
booklanguage: JP
monofont:
  - "Ricty Discord"
  - "M+"
jmonofont:
  - "Ricty Discord"
  - "M+"
link-citation: yes
colorlinks: yes
fontsize: 11pt
params:
  gamever: 2024.07.07.0
---


# 概要 {-}

:::{.infobox .caution data-latex="{caution}"}

Hellish Quart は現在アーリーアクセス状態です. 仕様が頻繁に変更されることに注意してください. このドキュメントは **`r params$gamever`** 準拠のものです.

:::

Steam アーリーアクセス版が発売中のインディーズ対戦ゲーム [Hellish Quart](https://store.steampowered.com/app/1000360/Hellish_Quart/?l=japanese)を私はまだ全然遊べていないが, かなりコアなゲームなので解説をしてみる. そもそも公式にも技コマンド表とかが充実してない 
(3月から全キャラ公開された) ので, 戦術の研究の一助になれば幸いである.

```{css, echo=F}
.gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}
.gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
.gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}
.gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}
.gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
.gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}
.gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}
.gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}
.gt_column_spanner_outer:first-child {
  padding-left: 0;
}
.gt_column_spanner_outer:last-child {
  padding-right: 0;
}
.gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}
.gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}
.gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}
.gt_from_md > :first-child {
  margin-top: 0;
}
.gt_from_md > :last-child {
  margin-bottom: 0;
}
.gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}
.gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}
.gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}
.gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}
.gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}
.gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}
.gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}
.gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}
.gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
.gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}
.gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}
.gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}
.gt_left {
  text-align: left;
}
.gt_center {
  text-align: center;
}
.gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
.gt_font_normal {
  font-weight: normal;
}
.gt_font_bold {
  font-weight: bold;
}
.gt_font_italic {
  font-style: italic;
}
.gt_super {
  font-size: 65%;
}
.gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
```

```{r include=F}
require(tidyverse)
require(gt)
knitr::opts_chunk$set(message = F, echo=F, warning = F, results = "asis")

d <- data.frame(
  icon_num = factor(1:4, levels = 1:5),
  xbox = c("X", "Y", "A", "B"),
  key = c("T", "Y", "G", "H"),
  ps = c("□",  "△", "❌",  "○"),
  x = c(0, 1, 0, 1),
  y = c(1, 1, 0, 0)
  #x = c(0, 0.5, 0.5, 1),
  #y = c(0, sqrt(2)/2, -sqrt(2)/2, 0)
)
d_direction <- tibble(
  icon_num = factor(1:4, levels = 1:5),
  xbox = c("U", "D", "L", "R"),
  key = c("U", "D", "L", "R"),
  x = c(.5, .5, 0, 1),
  y = c(1, 0, .5, .5)
)

ragg_png_mod <- function(...){
  ragg::agg_png(..., units = "in", res = 300)
}

ragg_png_mod <- function(...){
  ragg::agg_png(..., units = "in", res = 300)
}

make_buttons <- function(buttons, type = "xbox", dev = ragg_png_mod, save = T, dir = NULL, name = paste0(paste(buttons, collapse = "+"), ".png")){
  g <- d %>% mutate(!!sym(type) := if_else(key %in% buttons, !!sym(type), NA_character_)) %>%
    ggplot(aes(x = x, y = y)) +
    geom_point(
      aes(color = "black", fill = factor(if_else(!is.na(!!sym(type)), as.integer(icon_num), as.integer(5)), 1:5)),
      size = 15 * .pt, shape = 21, color = "black") +
    geom_text(aes(label = !!sym(type)), size = 10 * .pt) +
    coord_fixed(xlim = c(0 -1/.pt, 1 + 1/.pt), ylim = c(0, 1)) +
    scale_fill_manual(guide = F, breaks = factor(1:5), values = c("blue", "yellow", "green", "red", "grey")) +
    theme_void()
  if(save){
    ggsave(plot = g, device = dev, path = dir, filename = name)
  } else {
    return(g)
  }
}

make_direct_buttons <- function(
  buttons, dev = svglite::svglite, save = T, dir = NULL,
  name = paste0(paste(buttons, collapse = "+"), ".svg")
  ){
  dat <- d_direction %>% mutate(col := key %in% buttons)
  g <- ggplot() +
    aes(xend = x, x = 0.5, yend = y, y = .5, color = col) +
    geom_segment(arrow = arrow(angle = 45, length = unit(5 /.pt, units = "mm"), type = "closed"),
                 lineend = "butt", size =  4 /.pt, linejoin = "mitre", data = filter(dat, !col)) +
    geom_segment(arrow = arrow(angle = 45, length = unit(5 /.pt, units = "mm"), type = "closed"),
                 lineend = "butt", size =  4 /.pt, linejoin = "mitre", data = filter(dat, col)) +
    scale_color_manual(guide = F, breaks = c(T, F), values = c("black", "grey")) +
    coord_fixed(xlim = c(0 -1/.pt, 1 + 1/.pt), ylim = c(0 - 1/.pt, 1 + 1/.pt)) +
    theme_void()
  if(save){
    ggsave(plot = g, device = dev, path = dir, filename = name, width = 230/ (.pt * 200), height = 230 / (200 * .pt), standalone = F)
  } else {
    return(g)
  }
}

reuse_svg <- function(id){
  sprintf('<svg height=40 width=40><use xlink:href="#%s" /></svg>', id)
}

replace_keys <- function(text){
  text %>% str_remove_all("\\s") %>%
    str_match_all("\\[([TYGHRLUD\\+]+?)\\]|[^\\[([TYGHRLUD\\+]+?)\\]]+") %>%
    map(~tibble(str = if(length(.x[, 1]) == 0) "" else .x[, 1]) %>% mutate(
      is_key = str_detect(str, "\\[([TYGHRLUD\\+]+?)\\]"),
      str = if_else(is_key,
                    # str_replace_all(str, "\\[([TYGHUDLR\\+]+?)\\]", "img/\\1.svg") %>%
                    str_replace_all(str, "\\[([TYGHUDLR\\+]+?)\\]", "key-\\1") %>%
                      sapply(reuse_svg) %>%
                      unlist,
                    str),
    )
    ) %>% map_chr(~paste(.x$str, collapse = ", ") %>% str_remove("^,\\s"))
}
```

```{r eval=F}
a <- map_df(list.files("commands/", pattern = "*.csv", full.names = T), read_csv)$command %>%
  unique %>%str_remove_all(" ") %>%
  str_remove_all("or") %>%
  str_replace_all("\\]\\[", "] [") %>% 
  str_extract_all("\\[.+\\]") %>% unlist %>% str_split(" ") %>% unlist %>% unique
a %>% str_remove_all("\\[|\\]") %>% str_split("\\+") %>%
  walk(~make_buttons(.x, type = "key", dir = "img"))

c("U", "D", "L", "R") %>%
  walk(~make_direct_buttons(.x, type = "xbox", dir = "img"))
```

```{r}
to_table <- function(d, lr = F){
  t <- d %>% mutate(
    name = paste(name_orig, paste0("<br>(", name, ")")),
    mode = factor(mode, levels = c("normal", "long", "low", "high", "iron", "donna", "boartusk", "holy", "roof", "fool", "misc"))
    ) %>%
    dplyr::select(-name_orig)
  if(lr){
    t <- t %>% mutate(
      common = is.na(lr),
      lr = if_else(common, "l", lr)) %>%
      pivot_wider(id_cols = c(mode, name, common), names_from = lr, values_from = command) %>%
      mutate(l = if_else(is.na(l), "x", l), r = if_else(common, "", if_else(is.na(r), "x", r))) %>%
      dplyr::select(-common) %>% mutate(across(c(l, r), replace_keys))
  } else{
    t <- dplyr::select(t, -one_of("lr")) %>% mutate(command = replace_keys(command))
  }
  t <- t %>% arrange(mode) %>% group_by(mode) %>% gt()
  # HTMLをエスケープする方法として tab_row_group を使うものがあるが, rownames が表示されたままになる
  # 存在しないグループを指定するとエラー
  # よって内部データを改ざんするしかない
  g_headings <- list(
      normal = "通常時",
      long = "ロングガード時 - [スペース] 押しっぱなし",
      low = html(
        sprintf("下段の構え時 - %s + [スペース] 押しっぱなし)",
                paste(reuse_svg("key-D"), collapse = "\n"))
        ),
      iron = html(
          sprintf("〈鉄の門〉の構え時 - %s + [スペース] 押しっぱなし",
                  paste(readLines("img/D.svg"), collapse = "\n"))
          ),
      high = html(
          sprintf("〈上段〉の構え時 (%s + [スペース] 押しっぱなし)",
                  paste(reuse_svg("key-U"), collapse = "\n"))
          ),
      boartusk = html(
        sprintf("〈猪の牙〉の構え時 (%s + 「スペース」押しっぱなし)",
                paste(reuse_svg("key-U"), collapse = "\n"))
      ),
      donna = html(
        sprintf("〈貴婦人〉の構え時 (%s  %s %s)",
                paste(reuse_svg("key-D"), collapse = "\n"),
                paste(reuse_svg("key-L"), collapse = "\n"),
                paste(reuse_svg("key-Y"), collapse = "\n")
                )
      ),
      holy = html(sprintf("〈聖なる〉構え時 (%s)", paste(reuse_svg("key-D"), reuse_svg("key-R"), reuse_svg("key-Y"), collapse = "\n"))),
      roof = html(sprintf("〈屋根〉の構え時 (%s + [スペース] 押しっぱなし)", reuse_svg("key-U"))),
      fool = html(sprintf("〈愚者〉の構え時 (%s + [スペース] 押しっぱなし)", reuse_svg("key-D"))),
      misc = html(" ")
    )
    t$`_stub_df`[["group_label"]] <- map(t$`_stub_df`[["group_label"]], ~html(g_headings[[.x]]))
  if(lr){
    t <- t  %>%
      cols_label(name = "名称", l = "左足が前", r = "右足が前") %>%
      tab_spanner("コマンド", columns = c("l", "r")) %>%
      fmt_markdown(c("l", "r"))
  } else {
    t <- t %>%
      fmt_markdown(columns = "command") %>%
      cols_label(name = "名称", command = "コマンド")
  }
  t %>% fmt_markdown(columns = "name") %>% fmt_markdown(columns = "mode")
}
```

```{r}
# gt から不要なHTMLタグを削除する
as_html_table <- function(gt){
  x <- as_raw_html(gt, inline_css = F) %>% xml2::read_html()
  xml2::xml_remove(xml2::xml_find_all(x, "//style"))
  xml2::xml_child(xml2::xml_child(x)) %>% paste(collapse = "") %>% knitr::raw_html()
}
```


```{r, results="asis", echo=F}
# なんで勝手にpタグ混入するの?
cat(readLines("img/buttons.svg"), sep = "\n")
```

