## キャラクター一覧

いまのところこういうキャラクターがいる.^[Development Roadmap によれば, 最終的に12種類程度のキャラクターを用意したいらしい] ゲーム情報サイトとかでは17世紀の西洋剣術という触れ込みで報じてるが, 実は元ネタの剣術の使われた時期は15~19世紀とけっこう幅がある. だが開発者は「17世紀頃のポーランドと何らかの接点があったという歴史的裏付けがあるものを採用する方針」と言ってたので, サムライとかカタナとかニンジャとかの参戦は期待しないほうがいいだろう.

* サーベル
    * **ヤン** _Jan_, (旧ヤツェク, デリア着たままおじさん)
    * **ゲデオン** _Gedeon_ (肥満中年男性)
    * **バラバシ** _Barabasz_ (ウクライナコサック)
    * **ラースロー** _Laszlo_ (旧 _Haidu_, 隻眼)
    * **アレクサンデル** _Alexander_ (アフリカ系)
    * **サムエル** _Samuel_ (服がボロい)
    * **ヤツェク** _Jacek Dydyński_ (新ヤツェク)
    * **タルナフスキ** Tarnawski (勝利時に大笑いするおじさん)
    * **サヴァ** Sava (未登場)
* 長剣
    * **イザベラ** _Isabella_ (女長剣使い)
    * **ジェラ神父** _Father Żera_ (神父)
* レイピア
    * **マリー** _Marie_ (女レイピア使い)
    * **マルタ** _Marta_ (女レイピア使い, ドレス)
    * **カルクシュタイン** _Kalkstein_  (バスケットヒルトソード)
* その他
    * **ヨンドレク** _Jędrek_ (Yendrek) (民族衣装の斧使い)

その他, 短い初期型レイピア使い, 短剣を持ったコサックその2などが予告されている. なお, 新キャラクターを予告した直後のアップデートでまったく予告のないキャラクターが追加されたりするのはよくあるのであまり鵜呑みにしてはいけない.

2023年5月末のアップデートで, mod機能が追加された. サンプルの中には~~鉄拳の吉光のパチモンみたいな~~和風っぽいスキンに変えられたラースローが含まれている. これは和風キャラクターの登場と言えなくもない. だが, 外見を変えているだけで動きはいつものままなので, このゲームに惹かれる人たちが欲しがる機能なのか?と疑問に思っている.