## ラースロー/Laszlo {#Laszlo}

### 概要 {-}

比較的初期に追加された, 赤いドロマンを着たハンガリー風の隻眼の剣士である. 開発中の動画では Hajdu という名称で登場し, リリースされてからは Laszlo となっている. たぶんハンガリー語の László から来ているので, 本稿では「ラースロー」と表記している. 作者はラー「シュ」ローと発音しているが, ポーランド語なまりだろう.^[szはハンガリー語とポーランド語どちらでも使われる二重子音で, それぞれ発音が違う.]

ヤンと比べ, 肘から先だけを回す素早い連続攻撃が多いが, 上段の構えになると肘が無防備なので右上からの攻撃に弱い.

初期のバージョンではサバイバルモードで8連勝しないとアンロックされなかった. セーブデータを初期化するのが面倒なので今はどうなってるのか確認していない. 


### コマンド {-}

```{r laszlo}
map_df(list.files("commands/", pattern = "laszlo", full.names = T), read_csv) %>%
  bind_rows(read_csv("commands/misc_common.csv")) %>%
  to_table() %>%
  as_html_table
```

`</details>`{=html}

### 歴史的背景 {-}

このキャラクターは “Altin Elma” というハンガリーの武術研究団体の援助を受けて作成されたキャラクターらしい. https://www.facebook.com/AltinElmaEgyesulet/ Altin Elma 彼らはどうやらトランシルバニア公国, つまり近世のオスマン帝国領ハンガリーの軍事や武術に関心を持っているらしい. よって Lazlo はトルコの影響を受けたハンガリー人剣士, というデザインかもしれない. しかし開発者のコメントを総合すると, 服装はハンガリーのものを参考にしている^[襟の形なんかが特徴的だが, 3Dモデルの表現の問題なのか襟があまり立っていない. 前身頃の形状も変だ.]が, 鞘を握るポーズは[ある絵画](https://www.pinterest.jp/pin/1144125480307893411/)に基づいている. 攻撃動作は Siewiawski を参考にしているらしい. よって攻撃スタイルはハンガリーやトルコとあんまり関係ない.^[追記: Sieniawski 氏のスタイルは, ハンガリーや中東の影響が比較的強いが, 開発者がそこまで考えていたかはわからない.] …というか16世紀末-17世紀前半はポーランドとハンガリーは衣装の流行もほとんど同じで, サーベルもポーランドがハンガリーから取り入れたものなので, 現状名前がハンガリーっぽい以外にハンガリー独自要素があまりない…

リリース前に使われていた Haidu という名前は Hajduk からきているのだろう. 元々はトルコ語で野盗や山賊, あるいはそれと大差ない振る舞いをする非正規兵を指す言葉だったが, ハンガリー経由でポーランドに伝わった結果, ポーランドでは賊のニュアンスが消えて主に下級兵士のことを指す名詞として取り入れられた.

[:embed](https://www.pinterest.jp/pin/1144125480307893411/)

ちなみに, 17世紀頃のハンガリー剣術に関する英語で書かれた本を, 私は1つだけ知っている. だが, 当時の記録が少ないため, 多くを隣国の資料に基づいた推測に頼っており, 基本的な動作しか書かれていない.

更に言うと, Sieniawski を参考にしたといいつつ, Miklaszewskiの解説している「ハンガリー式」の動きと似た攻撃が多い気がする.

[:embed](https://www.youtube.com/watch?v=p6SSjn078lM)
