## イザベラ/Isabella {#Isabella}

### 概要 {-}

最初期から存在している長剣使いである. イタリア風のスタイルなので, 本稿ではイタリア語風に「イザベラ」と表記している.

[ゲデオン](#Gedeon)のように攻撃に合わせて左右の足が切り替わる. 足の左右が変わると**コマンドのほとんどが変わってしまう**ので覚えるのが大変である. さらに, ロングガード以外にも複数の構えがある. 長い剣でのアウトレンジ攻撃に目を奪われがちだが, いくつか存在する, 素早く切り返す連続攻撃も無視できない. ゲデオンと違いバックステップで左右が切り替わらないが, その代わりにその場で左右を切り替えるコマンドがある.

* 上段の構えは左右どちらからでも移行できる.
* 『鉄の門』の構えは左足が前の時のみ使用できる.
* 『猪の牙』の構えはその逆で, 右足が前のときのみ移行できる.
* 『貴婦人』の構え時は移動できず, 一定時間経過または前進や攻撃をすると解除される.

ちなみに v2023.12.05 現時点では, 貴婦人の構えの**本体のコマンド表のキーは間違っている**. Y ではなく X ボタンであり, なおかつ左右どちらからもできる^[https://steamcommunity.com/app/1000360/discussions/0/3419936083026348023/]. (元の文献でも左右両方の構えが書かれている) 以下の表ではこの誤記を修正した. 貴婦人の構えから派生する Heavy attack は左右どちらでもに出るのかはっきりしない.

### コマンド表 {-}

```{r isabella}
bind_rows(
  map_df(list.files("commands/", pattern = "isabella", full.names = T), read_csv)
  ) %>% bind_rows(read_csv("commands/misc_common.csv")) %>%
  to_table(lr = T) %>%
  as_html_table
```

### 歴史的背景 {-}

14-15世紀イタリアの武術家, Fiore d'ei Liberi の武術書に基づいた動きをしている. 開発者が動画で「Fiore の流派の長剣使いのキャラクターとして作ろうとしたが, Liechtenauer とごっちゃになってしまった」と述べている. この流派の動きを切れ目なく連続しているものが多いのでゲームに落とし込むのに苦労したらしい. そのため, かつては Fiore と 同時代のドイツの Lichtenauer 流の動きが混在していたが, アップデートでより純粋な Fiore の動きに寄せていく変更が何度かなされている. (しかし, 一度消えたLiechtenauer式のZwerhauが復活してしまった)

[:embed](https://www.pinterest.jp/pin/1144125480308815569/)

だが, 実際の17世紀イタリアで未だにFioreのスタイルを守っている人間がいたのかは分からない.
