## カルクシュタイン/Kalkstein {#Kalkstein}

### 概要 {-}

[:embed](https://www.youtube.com/watch?v=LDYyk-RKJnI)

2021.06.23のアップデートで追加された, スキアヴォーナを使用するキャラクターである. 出自に関する詳しい設定は明かされていないが, 本稿ではドイツ語風に「カルクシュタイン」表記にしている.

「彼の剣は重いため, 彼は力を入れる必要もなく, 素早く振ることもない」という設定のキャラクターらしい. ダメージは高めに設定されているようだが, 大ぶりでゆっくりした攻撃が多いので間合いを取るのが難しいかもしれない. コンボの2撃目が突きに変化することが多いのも特徴である. また, ゲデオンやイザベラのように足の向きでコマンドが変化する. デフォルトは右前で, 切替方法はこの2名とさらに異なり, **斜め移動**で左右の構えを切り替える. また, 一部の攻撃動作でも右前に切り替わるものがある.

### コマンド {-}

```{r kalkstein}
map_df(list.files("commands/", pattern = "kalkstein", full.names = T), read_csv) %>%
  bind_rows(read_csv("commands/misc_common.csv")) %>%
  to_table(lr = T) %>%
  as_html_table
```

### 歴史的背景 {-}

開発者は当初ボローニャ流にしようとしたが, 練習用に用意した剣が重かったので重い剣を活かしたアレンジを入れることを思いついたらしい. バスケットヒルトソードはスコットランドやスイスなどいろいろな地域・時代に見られ, 私はあまり見分けられる自信がないが, 作者の動画によればスキアヴォーナ (Schiavona) というタイプの剣だと言っている. これはルネッサンス-18cにヴェネツィア周辺で流行した剣である.^[参考: 三浦權利『西洋甲冑武器事典』柏書房), H. J. S. Withers "The Sword Encyclopedia of Swords and Sabers,"  Hermes House]. そっくりな形状の剣はポーランドの博物館にもあるようだ. 私もポーランド国内のいくつか博物館で見つけたことがある.

[:embed](https://www.pinterest.jp/pin/1144125480307894674/)

開発者はこれを元にしたとは明言していないが, ボローニャ流で最も有名な剣術家 Achille Marozzo の "Opera Nova" (16世紀前半の作) 2巻の片手剣の挿絵は確かに Kalkstein の姿勢とよく似ている.

[:embed](https://www.pinterest.jp/pin/1144125480309841680/)
[:embed](https://www.pinterest.jp/pin/1144125480309841676/)
[:embed](https://www.pinterest.jp/pin/1144125480309841674/)

キャラクターの設定ははっきりしていない. ヴェネツィアやユーゴスラヴィアで使われたスキアヴォーナを使用する, ドイツ語風の名前, イタリア式の戦い方, といった特徴から, オーストリアあたりの出身かもしれないと勝手に想像している.
