## ヤツェク/Jacek Dydyński {#Jacek}

### 概要 {-}

[:embed](https://www.youtube.com/watch?v=J9AWiNIvllc)

v2023.09.08から登場した. 登場に伴い, これまでパッケージ画像で中央にいて主人公っぽい雰囲気だったヤツェクと名乗っていたキャラクターは「ヤン \@{Jan}」に改名されてしまった.

真ヤツェクは, ゲデオンのような左右に大きく振る攻撃も, ラースローやアレクサンデルのような手元だけの出の早い連続攻撃もどちらも取り入れている. 左右の切り替えは同じ方向への攻撃と移動を同時に行うことでできる. あるいは後方へ飛び退くことで右に戻せる.

### コマンド {-}

```{r jacek2}
bind_rows(
  map_df(list.files("commands/", pattern = "jacek2", full.names = T), ~read_csv(.x, col_types = "c"))
  ) %>% bind_rows(read_csv("commands/misc_common.csv", col_types = "c")) %>%
  to_table(lr = T) %>%
  as_html_table
```


### 歴史的背景 {-}

初期から存在したヤツェクの元になった, 小説 Diabeł Łańcucki の主人公である. この小説はフィクションだが, さらにその原型となった17世紀の人物が実在する. 著作権の許可が取れたのか, 旧来のヤツェクの名前を奪って登場した. 開発者の投稿した動画では, モーションアクターのアントニ゠オルブリフスキ (Antoni Olbrychski) が大々的に宣伝されている. 以前の動画でも何度か映っていた彼は, 長剣を始め, 剣術選手権で優れた成績を収めている. また, 映画好きの人は知っているかも知れない, 俳優ダニエル゠オルブリフスキの孫でもある. ヤツェクのスタイルについても Miklaszewski 氏に質問したところ, これもサムエル同様オルブリフスキ氏のスタイルが強く反映されているらしい. 剣の振り方はサムエル同様イタロ゠ハンガリアン式で, 頻繁に足が切り替わるのは彼のもう1つの専門であるドイツ式長剣術の影響だろう, と言っていた.

こっちはかなり前にオルブリフスキ氏の所属している Akademia Szermierzy の公開した動画で, 本人も出演している. (ここで使われてる衣装の作者を知っている気がする...)

[:embed](https://www.youtube.com/watch?v=QttVCVXe8tc)

これも古いが, 祖父と共に実演している(アントニオルブリフスキファンクラブ個人サイトみたいになってきた)

[:embed](https://www.youtube.com/watch?v=M8Wp1DsfDDI)
