---
title: キャラクター別の難易度
---

# キャラクター別の難易度 {-#sec-difficulty}

## なぜ「弱い」キャラクターがいるのか

現時点では, チュートリアルが教える戦法を守っても成果につながらないことがよくある. これは, キャラクターによって運用思想が異なるにも関わらず, チュートリアルでは1種類の使い方しか教えていないためか, あるいは調整不足のためである. チュートリアルでは, パリィとリポストのラリーを繰り返すという, 近代的なフェンシング風の方法論が紹介されている. しかしながら, Hellish Quart に登場するスタイルは古いもので14世紀まで遡る. 古い時代の剣術は, そもそも動きを防御と攻撃に分解して考えるという発想が見られない, 根本的に異なるアプローチのものが多い. そういった古いスタイルのキャラクターは, チュートリアルの戦法を守っても強みを活かせない. 補足すると, このチュートリアルにある, 間合いを保つ訓練も, キャラクターごとに適した間合いは変わってくるので, 全てのキャラクターで有効とは言えない. これが, 使いにくい, ひいては弱いと見なされるキャラクターがいる理由だと考える.

もちろん, あくまでゲーム上のことなので, 完全に設定どおりということはない. そこで, 私が見た範囲で, パリィ・リポスト方式に当てはまらないスタイルのキャラクターを具体的に挙げてみる.

* ヨンドレク
* ジェラ神父
* イザベラ
* ラースロー
* ゲデオン
* アレクサンデル
* タルナフスキ

(全体の半分近くが該当してるじゃねえか)

ヨンドレクはそもそも武器が剣ではないので, 予備知識がなくとも変則的なキャラクターだとわかるので補足説明は不要だろう.

ジェラとイザベラは, ともに17世紀よりはるかに古い, 中世後期の剣術に則している. 使ったり対戦したりすると気づくと思うが, これらが攻撃しているのに押し負けるということがよくある. これは単に物理演算の結果だけでなく, 攻撃動作が防御も兼ねた太刀筋であることも影響している.

ラースローとゲデオンも, 「弱い」キャラクターであるという評判がある. いずれも自動防御の姿勢に隙が多く, 攻撃時に腕を大きく動かすため小手を取られやすいためであろう. ゲデオンはそれ抜きにしても本当に使いにくいが…

アレクサンデルも自動防御はそこそこ使えるが, カポエイラを混ぜた独特な動きのため, 一部の場面で自動防御に大きな隙ができる. タルナフスキも, 攻撃のリーチが長い代わりに予備動作や攻撃後の隙が大きい動作が多い.

## 歴史上の剣術のパラダイム

パリィ・リポスト方式でうまく戦えないキャラクターはどうするかというと, 以下の2通りのアプローチを研究する必要があると思う.

* ヒットアンドアウェイ方式
* ステッソ・テンポ方式

歴史的にも, パリィ・リポスト方式に当てはまらないスタイルの多くは, こう分類できそうである.

ヒットアンドアウェイは文字通り, 自動防御に頼らず, なるべく間合いの外から攻撃する. 剣の長いキャラクターならばやりやすい. リーチが無いキャラクターでも, 移動速度が速いキャラクターならば実践できることがある. 現実では, オスマン帝国がよく用いたスタイルだと示唆されている.

ステッソ・テンポ方式は, ヨーロッパで16世紀までよく見られた方式である. イタリアのマロッツォ (Marozzo) の文献に実際に stesso tempo という表現が使われているので, こう呼ぶことにした. これは攻撃と防御をワンテンポで行うという意味と解されている. 攻撃動作は常に, どこかの方向からの攻撃に対する防御を兼ねている. よって, 相手の全ての攻撃に対して, その方向からの攻撃を防ぎつつ, 相手の守られていない箇所に届くような太刀筋での攻撃を選択し, なおかつ連続して行う必要がある.

ステッソ・テンポは強力である一方で, 様々な攻撃に対してそれぞれ少なくとも1つ, 対抗手段を用意しなければならないため, 習得に時間がかかる. パリィ・リポストであれば, 全身を守りきれるだけの防御姿勢を覚えれば, 対処できる. 4つ程度の防御姿勢があれば, 多くの方向からの攻撃に対処できる. 歴史的には, 16世紀後半以降のヨーロッパでは, 鍔の形状が手元を守りやすいものに洗練されていくのに伴い, パリィ・リポスト方式の戦術が目立ってくる.

各キャラクターの動作セットはパリィ・リポスト方式の戦術に適したものもあれば, そうでないものもある. しかし, ゲーム内のチュートリアルではパリィ・リポスト方式しか教えておらず, カウンター攻撃は「リスキーな手段である」としか紹介されてないため, 上記のキャラクターの適切な使い方の学習機会がない.

## パリィ・リポストすべきでないスタイル

マリーはサルバドル゠ファブリス (Salvador Fabris) のスタイルを参考にしている. これは典型的なパリィ・リポスト方式である. サムエルやヤツェクも近代フェンシングの下地になったスタイルなので, パリィ・リポスト方式である. これらのキャラクターはいずれも, 攻撃時に自分の剣で相手から利き腕を隠すように攻撃するため小手を狙われにくく, かつ自動防御の性能が優れている傾向にある. (ただし, マリーは頭の防御が少し弱い)

もちろん, 例外もある. カルクシュタインの参考であるマロッツォ流はパリィ・リポスト方式でないはずだが, 彼の防御姿勢は堅牢である. しかし, 攻撃時は腕を大きく振る.

ヨンドレクは, ヒットアンドアウェイ向きだろう. 一回使えばわかる.
イザベラとジェラは, 剣が長いためアウトレンジ攻撃がしやすいが, 多くの攻撃は広い範囲に届き, 運動エネルギーが大きいので相手の剣を弾きやすい. よって考え方はステッソテンポでいいだろう.

アレクサンデルは, 特徴的な移動アニメーションも相まって, ヒットアンドアウェイ向きだろう.

ラースローは足が早く, 太刀筋も広くいろいろな方向への攻撃が用意されており, 相手の剣に当てやすいため, ステッソテンポとヒットアンドアウェイどちらの方式でも活躍できそうである. タルナフスキは, 足が速いわけではないが, 大きく踏み込む攻撃や, 攻撃範囲の広さと太刀筋の多様さが特徴なので, やはり両方のスタイルを利用できそうである.

ゲデオンは足が遅いのでステッソテンポ以外の選択肢がない. 左右のステップは速いので, 横移動限定でならヒットアンドアウェイと言えなくはない. 満遍なく全方向の攻撃ができるので, なんとか得意な間合いに持ち込まなければならない. 近い間合いで戦うところは元のスタイルと似ているが, それ以外の再現がいい加減である. 特に防御姿勢はぜんぜん違う. そして自動防御は隙だらけなのでリポストをするのは難しい. 特に突きはこちらが対抗手段を持たないこともあり, 苦戦する. 左右ステップや攻撃動作に伴う重心移動を活用した, 常にギリギリの戦いが要求される.

## 使いやすいキャラクターについて

ここで挙げなかったキャラクターは, 全てのパリィ・リポスト方式のキャラクターだと考えている. これらはチュートリアルで説明されるように, パリイ・リポストのラリーを続けると戦いやすい. そして, その中でも特に使いやすいキャラクターは以下だろう

* ヤン
* バラバシ
* サムエル

これらは自動防御の隙が少なく, 変わった攻撃動作も少ないため, コマンド表を暗記しなくてもある程度戦えるため, 初心者向けという意味である. サムエルは, 使う場面が限定されるフェイント攻撃が多いが, 基本的には隙が少ない. ヤツェクも入れようかと思ったが, 左右の切り替えがややテクニカルなので除外した. マリーも比較的使いやすい部類だが, 払い攻撃は隙を生みやすいので, 間違えて使わないようにコマンドを覚える必要がある.
