---
title: 用語集
---

# 用語集 {#sec-glossary}


Hellish Quart はよくある格闘ゲームとは違い, ターン制のような展開になる. その上西洋剣術が特徴であるため. 日本語にない概念が多く存在する. 以下はHQに使えそうな用語適当に選んだ. 多くは現代フェンシングのルール用語から取ってきている.

## ゲーム内用語

### スタミナ

キャラクターが特定の行動をすることで消費する状態変数のことを指す. 開発者はスタミナと言ったり condition と言ったりしており, 統一されていない. 攻撃をする, 攻撃を受ける, 剣を弾かれる, ステップ移動する, などで減少し, これらをしないでいると回復する. スタミナの最大値は現在のHPに依存する. 開発者はスタミナと言ったり耐久と言ったりして用語を統一していない. スタミナが減ると動きが遅くなったり, 構えが崩れたりするというペナルティが発生する. キャラクターのスタミナが低下している状態では, 画面端が青く点滅する.


### HP

開発者は health と呼んでいる. いわゆるHPのこと. 多くの攻撃は一撃でも受ければ即死だが, 内部的にはHPが設定されている. 部位ごとに設定されており, 頭と利き腕が最も最大HPが低い. いずれかの部位のHPがゼロになると負ける. 威力の低い攻撃をHPの高い部位に当てても一撃で勝負がつかないことがある. F4キーまたはコンフィグで現在のHPを表示でき, F5でダメージを表示できる.


### カウンター

相手の攻撃に合わせてこちらも攻撃すること.


### パリィ

parry. フランス語では parade という. 武器で相手の攻撃を防御することを意味する. このゲームではリアルタイムで当たり判定があるが, 開発者は, 自動防御で攻撃を防ぐことをパリィと表現し, 攻撃に攻撃を合わせて防ぐ行為をカウンターと表現することが多い.


### リポスト

フランス語の riposte. パリィしてから直ちに反撃すること. 一部のキャラクターやコマンドには速くリポストを返せる特性がある. なおパリィはフランス語ではパラード (parade) という.


### コントルリポスト

フランス語の contre-riposte. リポストに対してさらに反撃することを指す. 開発者の戦術解説動画でやり方のヒントが紹介されている.


### グラップリング

grappling. 掴み技のことを指す. 長いので掴みって書いたほうが早いと思う. 全てのキャラクターが持つ共通コマンドである. 成功時のアニメーションはキャラクターによって異なる.


### 押しのける

コマンド表で push と書かれている技のことを指す. 全キャラクターが持つ共通コマンドで, 手の届く距離まで肉薄したときに, 相手の利き腕を押して構えを崩せる. あまり使いどころのないコマンドだが, キャラクターによっては持続時間が長く, ポメル殴りよりも有効なことがある.


### フェイント

ゲーム内でフェイント効果付きの攻撃もあるし, 対人戦で相手のミスを誘うための運用も意味する.


### 相打ち

英語では double kill という. HQでは頻繁に相打ちによる引き分けが起こる.


### 攻撃優先権

フェンシングのルールに擬した Right of Way モードと, そのルールのこと. フェンシングの用語では phrase d'arme といい, HQでは英語で right of way と表現される.

## 武術用語

### フォント

フランス語の fente. 後ろ足を伸ばして前足を曲げることで, 前に飛び出す突き攻撃のこと. HQのコマンド表ではlungeと書かれていることが多い.


### シュタルク

ドイツ語の形容詞 Stark. 硬い, 力強いという意味で, 刀身の根本側の部分を指す. 鋼は靭性があり, 根元ほどしなりにくい. HQの物理演算のため, 相手の攻撃は剣のシュタルクな箇所で防いだ方が望ましい.


### シュヴァッヒ

ドイツ語の形容詞 Scwach. 柔弱という意味で, シュタルクの対義語である. 刀身の先端に近い側をこう呼ぶ. 攻撃の多くは剣のシュヴァッヒな部分を相手に当てるようになされるが, 受け止められやすい部位でもある.


### スタイル

きわめておおまかに言えば, 「流派」と同義語とみてよい. 欧州の武術には日本のように一子相伝で後継者を作る作法はないため, 同一の概念と見ることは正確ではないため, あえて「スタイル」と書いている. 「方法論」と言ったほうが近いかもしれない.

### バインディング

binding. ロングガード時に, 相手の突き攻撃を巻き取るような動作で防ぐことを指す. おそらくドイツ語の binden を英語に置き換えたものだが, ゲーム内の動作は binding というより changement のように見える.

### バッテ

フランス語の battement. こちらに切っ先が向いている相手の剣を叩いて切っ先を反らすことを指す. バッテマンと書くのが正確だろうが, 長いのでバッテと言う人が多い. ロングガード時の剣を叩くと容易に構えが大きく崩れ, 効果音もいつもより大きくなる.


### デガジュ

フランス語の dégagement. 相手のバッテに対して剣を引っ込めて回避することをいう. 本来の用法は少し違うが意図はだいたい同じだと思う. これも略して言う人が多かった.


### 構え

特定のコマンドで, キャラクターの姿勢を変えられる. ほぼすべてのキャラクターはロングガードの構えが用意されており, 一部はさらに他の構えを使用できる. 構えを変更すると, 防御姿勢や使用できるコマンドが変化する
ロングガード ほぼすべてのキャラクターが可能な, 腕を伸ばして剣を突き出した構えのこと. 自動防御の特性と, 攻撃動作が通常とは異なる. 概して, 突き攻撃の防御がしやすくなり, こちらも突き攻撃をすることが多い.


### 上段攻撃

上半身を起点とした攻撃のこと. 基本的には2つのボタンにそれぞれ対応した2通りある. 斬り下ろしだったり, 水平方向の横払いだったり, キャラクターやコマンドによって太刀筋は異なる. 他の多くの格ゲーとは異なり, HQは攻撃を上段下段(あるいは中段)に分けて防御判定することはない.


### 中段攻撃

下半身を起点とした攻撃のこと.  攻撃ボタンでは下の2つに対応するが, 少数存在する足元だけを狙った攻撃と区別するため, 中段と呼んでいる. 以降上段攻撃と同じ. 


### 下段攻撃

足元を狙った攻撃のことを指す. ほとんどのキャラクターに1つか2つこのコマンドがある. 同様に, ほとんどのキャラクターには専用のカウンター動作が用意されている. たまに暴発する.


### 上段構え

剣を高めに掲げる構えのこと. 自動防御の姿勢は含めない. よくある格ゲーと異なり, HQには攻撃を上段下段(あるいは中段)で判定するルールはない.

### 下段構え

上段と同じ.


### 右前・左前

キャラクターの姿勢が右足と左足のどちらを前に出しているかを表す.


### ステップ

方向キーを同じ方向に2度押しすることで発生する動作のことを指す. 瞬時に間合いを調整したい時に使う. スタミナを消費する. ステップの瞬間は自動防御も無効になるので, 乱用はしないほうがよい. 


### めくり

このゲームではジャンプができないが, いくつかの動作でキャラクターの自動方向調整がバグって明後日の方向を向き, 大きな隙ができることがある. 便宜的に格ゲー業界で昔から使われている用語を使い, めくりと呼ぶ. 調整不足なのか, こっちが攻撃してるのに勝手にめくれて自滅する動作がいくつかある.


## 武器


### 長剣

long sword. 両手で扱うことを想定した長めの剣で, 特に中世後期のドイツで盛んに使用された. 当時の文献では Langschwert, Langes Schwert などと書かれている. 現在では, これをそのまま英語に訳して long sword という名前でよく呼ばれている.


### 裏刃

false edge, ドイツ語では kurze schneide^[中世の剣術用語なので, たぶん現代的な用法ではない] という. 自分に近い側の刃, あるいはその刃で攻撃すること. 両刃の長剣使いが多用し, 一部のサーベル使いも使用する. 裏刃を使った攻撃は変則的な太刀筋になりやすいので, フェイントとして有効なことがある.


### ポメル

pommel. 剣の柄頭のことを指す. 相手との間合いが近すぎると, ほとんどの攻撃は自動でポメルを使った殴り動作に切り替わる. 現実のマニュアルでも, 相手に近づきすぎた場合は刃で切るより殴りつけることを推奨するものがよくある.


## その他

広く使う機会が少なさそうだが, ついでに書いとく.

### フレッシュ

フランス語の Flèche. 突き姿勢のまま走り抜けること. ヤツェクのコマンド表にこの技があるが, 相手の手前で止まってしまうという隙の大きい攻撃になっている.
